# Generated by Django 3.2.5 on 2022-06-12 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=12, verbose_name='Access Password')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Name')),
                ('coordinates', models.JSONField(null=True, verbose_name='Location Coordinates')),
                ('lat', models.FloatField(max_length=24, null=True, verbose_name='Latitude center of coordinates')),
                ('long', models.FloatField(max_length=24, null=True, verbose_name='Longitude center of coordinates')),
                ('width', models.IntegerField(default=3, verbose_name='Width of the map')),
                ('height', models.IntegerField(default=5, verbose_name='Height of the map')),
                ('coordinate_type', models.CharField(choices=[('MultiPolygon', 'MultiPolygon'), ('Polygon', 'Polygon'), ('Point', 'Point')], default='MultiPolygon', max_length=20, verbose_name='Coordinate Type')),
                ('nearby_locations', models.JSONField(blank=True, null=True, verbose_name='All the locations inside the coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Location name')),
                ('city_name', models.CharField(max_length=300, null=True, verbose_name='City Name')),
                ('state_name', models.CharField(max_length=300, null=True, verbose_name='State Name')),
                ('population', models.CharField(max_length=255, null=True, verbose_name='Population')),
                ('location_id', models.CharField(max_length=100, null=True, verbose_name='Location id')),
                ('location_map', models.CharField(max_length=300, null=True, verbose_name='Location map')),
                ('lat', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Latitude')),
                ('lng', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Longitude')),
                ('can_retrive_population', models.BooleanField(default=True, verbose_name='can retrive population')),
            ],
        ),
        migrations.CreateModel(
            name='Util',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_media_url', models.URLField(blank=True, null=True, verbose_name='Verify media url')),
                ('insta_sessionid', models.TextField(blank=True, help_text='Insert instagram sessionid separated by comma', max_length=512, null=True, verbose_name='Instagram Session Id')),
                ('about_text', models.TextField(blank=True, null=True, verbose_name='About Text')),
                ('turn_on_filtering', models.BooleanField(default=False, verbose_name='Turn on Post filtering')),
            ],
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True, verbose_name='Warning start time.')),
                ('end_time', models.DateTimeField(null=True, verbose_name='Warning end time.')),
                ('warning_type', models.CharField(choices=[('TORNADO', 'Tornado'), ('FLOOD', 'Flood'), ('TSTORM', 'Thunderstorm')], default='TORNADO', max_length=20)),
                ('warning_label', models.CharField(blank=True, max_length=120, null=True, verbose_name='Warning Label')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='app.location')),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tag Name')),
                ('post', models.CharField(blank=True, max_length=255, null=True, verbose_name='Post (automatic field)')),
                ('users', models.ManyToManyField(blank=True, null=True, to='app.AccessPassword', verbose_name='Users Belong This Tag')),
            ],
        ),
    ]
