# Generated by Django 3.2 on 2021-04-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Hash tag name')),
                ('post', models.CharField(max_length=255, verbose_name='How many post related this tag')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Location name')),
                ('location_id', models.CharField(max_length=100, verbose_name='Location id')),
                ('population', models.CharField(max_length=255, verbose_name='Population')),
                ('location_map', models.CharField(max_length=300, null=True, verbose_name='Location map')),
            ],
        ),
    ]
