# Generated by Django 3.2.5 on 2022-07-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspassword',
            name='height',
        ),
        migrations.RemoveField(
            model_name='accesspassword',
            name='width',
        ),
        migrations.AddField(
            model_name='accesspassword',
            name='lats_bounds',
            field=models.CharField(max_length=255, null=True, verbose_name='Lats Bounds'),
        ),
        migrations.AddField(
            model_name='accesspassword',
            name='lons_bounds',
            field=models.CharField(max_length=255, null=True, verbose_name='Lons Bounds'),
        ),
        migrations.AlterField(
            model_name='accesspassword',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='User Name'),
        ),
    ]
