# Generated by Django 3.2.5 on 2022-07-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220703_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspassword',
            name='lats_bounds',
            field=models.CharField(help_text='Enter lats separated by comma, eg. 23.11,20.1', max_length=255, null=True, verbose_name='Lats Bounds'),
        ),
        migrations.AlterField(
            model_name='accesspassword',
            name='lons_bounds',
            field=models.CharField(help_text='Enter lons separated by comma, eg. 100.11,205.1', max_length=255, null=True, verbose_name='Lons Bounds'),
        ),
    ]
