# Generated by Django 3.2.5 on 2021-07-24 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hashtag_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city_name',
            field=models.CharField(max_length=300, null=True, verbose_name='City Name'),
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='location',
            name='state_name',
            field=models.CharField(max_length=300, null=True, verbose_name='State Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='population',
            field=models.CharField(max_length=255, null=True, verbose_name='Population'),
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True, verbose_name='Warning start time.')),
                ('end_time', models.DateTimeField(null=True, verbose_name='Warning end time.')),
                ('warning_type', models.CharField(choices=[('TORNADO', 'Tornado'), ('FLOOD', 'Flood'), ('TSTROM', 'T Storm')], default='TORNADO', max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warning', to='app.location')),
            ],
        ),
    ]
