# Generated by Django 3.2.5 on 2022-07-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220703_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspassword',
            name='generate_new_big_map',
            field=models.BooleanField(default=True, help_text='generate new big map each time you visit the warning page', null=True, verbose_name='Generate big map'),
        ),
    ]
