# Generated by Django 3.2.5 on 2022-07-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_accesspassword_generate_new_big_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspassword',
            name='generate_new_big_map',
            field=models.BooleanField(default=True, help_text='generate new big map each time you visit the warning page', verbose_name='Generate big map'),
        ),
    ]
