# Generated by Django 3.2.5 on 2021-07-25 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210725_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warning',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='app.location'),
        ),
    ]
