# Generated by Django 3.2.5 on 2021-07-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_warning_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Tag Name'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='post',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Post (this field will populate automatically when you save)'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='warning_type',
            field=models.CharField(choices=[('TORNADO', 'Tornado'), ('FLOOD', 'Flood'), ('TSTORM', 'Thunderstorm')], default='TORNADO', max_length=20),
        ),
    ]
