# Generated by Django 3.2.5 on 2021-07-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210729_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='post',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Post (automatic field)'),
        ),
    ]
