# Generated by Django 3.2.5 on 2022-07-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_accesspassword_generate_new_big_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='util',
            name='zoom_label',
            field=models.CharField(blank=True, default='100%', help_text='Login page zoom label', max_length=10, null=True),
        ),
    ]
