# Generated by Django 3.2.5 on 2021-08-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_hashtag_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='can_retrive_population',
            field=models.BooleanField(default=True, verbose_name='can retrive population'),
        ),
    ]
