# Generated by Django 3.2.5 on 2021-12-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211216_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspassword',
            name='coordinate_type',
            field=models.CharField(choices=[('MultiPolygon', 'MultiPolygon'), ('Polygon', 'Polygon'), ('Point', 'Point')], default='MultiPolygon', max_length=20, verbose_name='Coordinate Type'),
        ),
        migrations.AddField(
            model_name='accesspassword',
            name='coordinates',
            field=models.JSONField(null=True, verbose_name='Location Coordinates'),
        ),
        migrations.AddField(
            model_name='accesspassword',
            name='lat',
            field=models.FloatField(max_length=24, null=True, verbose_name='Latitude center of coordinates'),
        ),
        migrations.AddField(
            model_name='accesspassword',
            name='long',
            field=models.FloatField(max_length=24, null=True, verbose_name='Longitude center of coordinates'),
        ),
        migrations.AddField(
            model_name='accesspassword',
            name='nearby_locations',
            field=models.JSONField(blank=True, null=True, verbose_name='All the locations inside the coordinates'),
        ),
    ]
