# Generated by Django 3.2.5 on 2022-01-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211221_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='app.AccessPassword', verbose_name='Users Belong This Tag'),
        ),
    ]
