# Generated by Django 3.2.5 on 2022-01-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_hashtag_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspassword',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User Name'),
        ),
    ]
