# Generated by Django 3.2.5 on 2022-01-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_accesspassword_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Util',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_media_url', models.URLField(blank=True, null=True, verbose_name='Verify media url')),
                ('insta_sessionid', models.TextField(blank=True, help_text='Insert instagram sessionid separated by comma', max_length=512, null=True, verbose_name='Instagram Session Id')),
                ('about_text', models.TextField(verbose_name='About Text')),
                ('turn_on_filtering', models.BooleanField(default=False, verbose_name='Turn on Post filtering')),
            ],
        ),
    ]
