# Generated by Django 3.2.5 on 2022-01-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_util'),
    ]

    operations = [
        migrations.AlterField(
            model_name='util',
            name='about_text',
            field=models.TextField(blank=True, null=True, verbose_name='About Text'),
        ),
    ]
