# Generated by Django 3.2.5 on 2022-02-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_util_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspassword',
            name='height',
            field=models.IntegerField(default=5, verbose_name='Height of the map'),
        ),
        migrations.AddField(
            model_name='accesspassword',
            name='width',
            field=models.IntegerField(default=3, verbose_name='Width of the map'),
        ),
    ]
