# Generated by Django 3.2.5 on 2022-06-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220207_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='status',
            field=models.CharField(default=None, max_length=120, verbose_name='Warning status'),
        ),
    ]
