# Generated by Django 3.2.5 on 2022-06-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_warning_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warning',
            name='status',
        ),
        migrations.AddField(
            model_name='warning',
            name='warning_label',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Warning Label'),
        ),
    ]
